### ISSUE TITLE
Corrigir a constante PHP_VERISON para PHP_VERSION

### ISSUE THREAD

**Issue by dilowagner** [alhaag/docker-php-mysql-nginx#1]
A constante no env.example está incorreta a nomenclatura
PHP_VERISON
mudar para
PHP_VERSION

**Comment by alhaag** [comment]
Obrigado Diego,
Corrigido no commit: https://github.com/alhaag/docker-php-mysql-nginx/commit/b29372d5fe25e935ccf187f93d94239e9d9f076d
